remote_theme: JetBrains/oss-site-jekyll-theme

project_name: 'Ktor'
header_logo_url: 'assets/images/ktor_logo_white.svg'
render_toc_on_docs_layout: true
search: true

# Uncomment for local Docker preview
#theme: jetbrains-oss-jekyll-theme

plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from

url: https://ktor.io

repository: ktorio/ktorio.github.io
encoding: utf-8
output: web

# this appears in the html browser tab for the site title (seen mostly by search engines, not users)
title: Ktor
description: "Ktor"
url: http://ktor.io

ktor_version: 0.9.2
ktor_version_eap: 0.9.2
kotlin_version: 1.2.40

github_editme_path: ktorio/ktorio.github.io/edit/master/
google_analytics: UA-47631155-3

exclude:
  - .idea
  - .gitignore
  - Dockerfile
  - docker-build.sh
  - docker-run.sh

# library used for syntax highlighting
highlighter: rouge

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 entity_output: as_char
 toc_levels: 1..6
 smart_quotes: lsquo,rsquo,ldquo,rdquo
 syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
    values:
      layout: "docs"
